Mang 2/LTM2_Buoi1/Controllers/MoviesController.cs
using LTM2_Buoi1.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace LTM2_Buoi1.Controllers
{
    public class MoviesController : Controller
    {
        private MovieDBContext db = new MovieDBContext();

        // GET: Movies
        public ActionResult Index()
        {
            var movies = from m in db.Movies
                         select m;

            ViewBag.ListGenre = db.Movies.

            Select(x => new SelectListItem() { Text = x.Genre, Value = x.Genre }).Distinct().ToList();

            return View(movies);
        }

        public ActionResult Timkiem(string tieude, string genre, decimal? price)
        {
            var movies = from m in db.Movies
                         select m;
            if (!String.IsNullOrEmpty(tieude))
            {
                movies = movies.Where(s => s.Title.Contains(tieude) && s.Genre.Contains(genre) && s.Price >= price);
            }
            return View("Index", movies);
        }

        //public ActionResult Upload(HttpPostedFileBase Picturefile)
        //{
        //    try
        //    {
        //        if (Picturefile.ContentLength > 0)
        //       {
        //            string FileName = Path.GetFileName(Picturefile.FileName);
        //            string path = Path.Combine(Server.MapPath("~/Picture"), FileName);
        //            Picturefile.SaveAs(path);
        //        }
        //        ViewBag.Message = "File uploaded successfully!";
        //        return View();
        //    }
        //    catch
        //    {
        //        ViewBag.Message = "File upload failed";
        //        return View();
        //    }
        //}

        // GET: Movies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // GET: Movies/Create
        public ActionResult Create()
        {
            List<SelectListItem> list = new List<SelectListItem>{
               new SelectListItem{
                   Value="1",
                   Text="Kiem hiep"
               },
               new SelectListItem{
                   Value="2",
                   Text="XHD"
               },
               new SelectListItem{
                   Value="3",
                   Text="Kinh di"
               }
           }.ToList();
            ViewBag.List = list;
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Title,ReleaseDate,Genre,Rated,Price,Picture")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                HttpPostedFileBase File = Request.Files["file"];
                db.Movies.Add(movie);
                movie.PictureUpload = File.FileName;
                File.SaveAs(Server.MapPath("~/Picture/" + movie.PictureUpload + ".jpg"));
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(movie);
        }

        // GET: Movies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Title,ReleaseDate,Genre,Rated,Price,Picture")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                HttpPostedFileBase File = Request.Files["file"];
                db.Movies.Add(movie);
                movie.PictureUpload = File.FileName;
                File.SaveAs(Server.MapPath("~/Picture/" + movie.PictureUpload + ".jpg"));
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(movie);
        }

        // GET: Movies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Movie movie = db.Movies.Find(id);
            db.Movies.Remove(movie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Mang 2/LTM2_Buoi1/Views/Movies/Create.cshtml
@using LTM2_Buoi1.Extention
@model LTM2_Buoi1.Models.Movie

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm(null, null, FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Movie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @html.labelfor(model => model.genre, htmlattributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @html.dropdownlistfor(model => model.genre, viewbag.list as ienumerable<selectlistitem>, new { htmlattributes = new { @class = "form-control" } })
                @html.validationmessagefor(model => model.genre, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Rated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rated, new { htmlAttributes = new { @class = "form-control rating" } })
                @Html.ValidationMessageFor(model => model.Rated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.summary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.summary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.summary, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file" required />
            </div>
        </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Mang 2/LTM2_Buoi1/Views/Movies/Delete.cshtml
@model LTM2_Buoi1.Models.Movie

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Picture)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Mang 2/LTM2_Buoi1/Views/Movies/Details.cshtml
@model LTM2_Buoi1.Models.Movie

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Movie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Picture)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Mang 2/LTM2_Buoi1/Views/Movies/Edit.cshtml
@using LTM2_Buoi1.Extention
@model LTM2_Buoi1.Models.Movie

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Movies", FormMethod.Post, new {enctype = "multipart/form-data", @class = "form-horizontal", role = "form"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Movie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.Picture)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @html.labelfor(model => model.genre, htmlattributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @html.dropdownlistfor(model => model.genre, viewbag.list as ienumerable<selectlistitem>, new { htmlattributes = new { @class = "form-control" } })
                @html.validationmessagefor(model => model.genre, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Rated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rated, new { htmlAttributes = new { @class = "form-control rating" } })
                @Html.ValidationMessageFor(model => model.Rated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.summary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.summary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.summary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Hinh hien tai", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ShowImage(Model.Picture)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file" required />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Mang 2/LTM2_Buoi1/Views/Movies/Index.cshtml
@model IEnumerable<LTM2_Buoi1.Models.Movie>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<script>
    function myFunction() {
        var timkiem =
            //$("#abc")
            //class="abc"; id=
            //document.getElementById("timkiem").value;
            $("#timkiem")[0]
            .value;
        var url = "http://localhost:49911/Movies/Index?searchString=" + timkiem;
        $("#ketqua").load(url);
        //document.location.href = url;
        //alert(url);

    }
</script>
<style>
    .col-sm-4 {
        padding:0px 10px;
        box-sizing:border-box;

    }
        .col-sm-4 span:nth-of-type(1) {padding-top:0px;padding-bottom:0px; padding-left:0px
        }
    .col-sm-4 span {
        width: 100%;
        padding:10px 0px;
        display: block;
        box-sizing:border-box;
        border-bottom:1px solid #805500;
        border-right:1px solid #805500;
        border-left:1px solid #805500;
        font-size: 130%;
        font-family: Arial;
        font-weight: bold;
        background-color:  #ccf5ff;
        padding-left:5px
    }
    .hinhanh img{width:100%; height: 200px;}
</style>
<h2>Index</h2>
<input type="text" id="timkiem" />
<button onclick="myFunction()">Timkiem</button>
<p>
    @Html.ActionLink("Create New", "Create")
</p>

<div  id="ketqua"></div>

{
    <p>
        Tieude: @Html.TextBox("Tieude") <br />
        Genre: @Html.DropDownList("Genre", (List<SelectListItem>)ViewBag.ListGenre)<br />

        @*<select id="Genre" name="Genre">
            <option value="1">fddfgf</option>
            <option value="2">dff</option>
        </select><br />*@

        Price: @Html.TextBox("Price") <br />
        <input type="submit" value="Filter" />
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Picture)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReleaseDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Genre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rated, new { htmlAttributes = new { @class = "rating" } })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            <img width="50%" height="200" src="https://pbs.twimg.com/media/DI-z3cOXoAIaPPA.jpg" />
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}
</table>

<div class="container">
    <div class="row">
@foreach (var item in Model) {
        <div class="col-sm-4">
            <span class="hinhanh"><img src="https://pbs.twimg.com/media/DI-z3cOXoAIaPPA.jpg" /></span>
            <span>@Html.DisplayFor(modelItem => item.Title)</span>
            <span>@Html.DisplayFor(modelItem => item.ReleaseDate)</span>
            <span>@Html.DisplayFor(modelItem => item.Genre)</span>
            <span>@Html.DisplayFor(modelItem => item.Rated, new { htmlAttributes = new { @class = "rating" } })</span>
            <span>@Html.DisplayFor(modelItem => item.Price)</span>
@using (Html.BeginForm(null, null, FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(model => model.ID)
}
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="MUA" class="btn btn-default" />
                </div>
            </div>
        </div>
}
    </div>
</div>